version: '3'
services:
  auth:
    build: ./auth-api
  users:
    build: ./users-api
    ports:
      - '5000:8080'
  tasks:
    build: ./tasks-api
    ports:
      - '6000:8000'
    environment:
      TASKS_FOLDER: tasks
