version: "3.9"
services:
    npm:
        build: ./
        stdin_open: true
        tty: true
        volumes:
            - ./:/app
    yarn:
        build: ./
        entrypoint: ["yarn"]
        stdin_open: true
        tty: true
        volumes:
            - ./:/app
