apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0264e97cc4f1d8906
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-efs-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: prbservicesllc/users:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: MONGODB_CONNECTION_URI
              value: 'mongodb+srv://phil_boyd_mongodb:fjcm2X@*dH&1!ss9@cluster0.7yy8u.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'
            - name: AUTH_API_ADDRESS
              value: 'auth-service.default:3000'
          volumeMounts:
            - name: users-efs-vol
              mountPath: /app/users
      volumes:
        - name: users-efs-vol
          persistentVolumeClaim:
            claimName: users-efs-pvc
