apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: prbservicesllc/users:mod-15
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: MONGODB_CONNECTION_URI
              value: 'mongodb+srv://phil_boyd_mongodb:fjcm2X@*dH&1!ss9@cluster0.7yy8u.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'
            - name: AUTH_API_ADDRESSS
              value: 'auth-service.default:3000'
