version: '3.9'

services:
    sonar:
        image: sonarqube:latest
        restart: always
        networks:
            - sonar-network
        ports:
            - 9000:9000

networks:
    sonar-network:
        name: sonar-network
