version: '3.9'

services:
    portainer:
        image: portainer/portainer:latest
        command: -H unix:///var/run/docker.sock
        restart: always
        ports:
            - 9200:9000
            - 8200:8000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer-data:/data

volumes:
    portainer-data: {}

networks:
    portainer-network:
        name: portainer-network
