version: '3.9'

services:
    localstack:
        # container_name: '${LOCALSTACK_DOCKER_NAME-localstack_main}'
        image: localstack/localstack
        network_mode: bridge
        networks:
            - localstack-network
        restart: always
        ports:
            - '4566:4566'
            - '4571:4571'
            - '${PORT_WEB_UI-8800}:${PORT_WEB_UI-8080}'
        environment:
            - SERVICES=${SERVICES- }
            - DEBUG=${DEBUG- }
            - DATA_DIR=${DATA_DIR- }
            - PORT_WEB_UI=${PORT_WEB_UI- }
            - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
            - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
            - DOCKER_HOST=unix:///var/run/docker.sock
            - HOST_TMP_FOLDER=${TMPDIR}
        volumes:
            - localstack-data:/tmp/localstack'
            - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
    localstack-data: {}

networks:
    localstack-network:
        name: localstack-network
